create database barbershop_project;

create extension if not exists citext;

create domain email AS citext
    check ( value ~
            '^[a-zA-Z0-9.!#$%&''*+/=?^_`{|}~-]+@[a-zA-Z0-9](?:[a-zA-Z0-9-]{0,61}[a-zA-Z0-9])?(?:\.[a-zA-Z0-9](?:[a-zA-Z0-9-]{0,61}[a-zA-Z0-9])?)*$' );

create table users
(
    id              SERIAL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    name            VARCHAR(50)  NOT NULL,
    surname         VARCHAR(50)  NOT NULL,
    birthdate       DATE,
    gender          gender,
    email           email UNIQUE NOT NULL,
    password        VARCHAR(250) NOT NULL,
    phone_number_id INTEGER      NOT NULL,
    created_at      TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at      TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (phone_number_id) REFERENCES phone_numbers (phone_number_id)
);

CREATE TYPE gender AS ENUM ('male', 'female');

create table phone_numbers
(
    phone_number_id        SERIAL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    national_operator_code BYTEA,
    phone_number           numeric(7, 0)
);


